var countriesStore = new Ext.data.Store({
    model: 'countriesModel',
    sorters: 'text',
    getGroupString : function(record) {
        return record.get('text')[0];
    },
    data:[		
          		  {text: '',  value: ''},
		          {text: 'Bangladesh',  value: 'BD'},
		          {text: 'Wallis And Futuna Islands', value: 'WF'},
		          {text: 'Burkina Faso', value:'BF'},
		          {text: 'Paraguay', value:'PY'},
		          {text: 'Bosnia And Herzegovina',  value: 'BA'},
		          {text: 'Barbados', value: 'BB'},
		          {text: 'Belgium', value:'BE'},
		          {text: 'Bermuda', value:'BM'},
		          {text: 'Brunei Darussalam',  value: 'BN'},
		          {text: 'Bolivia', value: 'BO'},
		          {text: 'Bahrain', value:'BH'},
		          {text: 'Burundi', value:'BI'},
		          {text: 'Benin',  value: 'BJ'},
		          {text: 'Bhutan', value: 'BT'},
		          {text: 'Jamaica', value:'JM'},
		          {text: 'Bouvet Island', value:'BV'},
		          {text: 'Botswana',  value: 'BW'},
		          {text: 'Samoa', value: 'WS'},
		          {text: 'Brazil', value:'BR'},
		          {text: 'Bahamas',  value: 'BD'},
		          {text: 'JerseyBY:Belarus', value: 'JE'},
		          {text: 'Belize', value:'BZ'},
		          {text: 'Russian Federation', value:'RW'},
		          {text: 'Rwanda',  value: 'BA'},
		          {text: 'Lithuania', value: 'LT'},
		          {text: 'Reunion', value:'RE'},
		          {text: 'Turkmenistan', value:'TM'},
		          {text: 'Tajikistan',  value: 'TJ'},
		          {text: 'Romania', value: 'RO'},
		          {text: 'Lesotho', value:'LS'},
		          {text: 'Guinea-bissau', value:'BI'},
		          {text: 'Guam',  value: 'GU'},
		          {text: 'Guatemala', value: 'GT'},
		          {text: 'South Georgia And South Sandwich Islands', value:'GS'},
		          {text: 'Greece', value:'GR'},
		          {text: 'Equatorial Guinea',  value: 'GQ'},
		          {text: 'Guadeloupe', value: 'GP'},
		          {text: 'Japan', value:'JP'},
		          {text: 'Guyana',  value: 'GY'},
		          {text: 'Guernsey', value: 'GG'},
		          {text: 'French Guiana', value:'GF'},
		          {text: 'Georgia', value:'GE'},
		          {text: 'Grenada',  value: 'GD'},
		          {text: 'Great Britain',  value: 'GB'},
		          {text: 'Gabon', value: 'GA'},
		          {text: 'Guinea', value:'GN'},
		          {text: 'Gambia', value:'GM'},
		          {text: 'Greenland',  value: 'GL'},
		          {text: 'Gibraltar', value: 'GI'},
		          {text: 'Ghana', value:'GH'},
		          {text: 'Oman', value:'OM'},
		          {text: 'Tunisia',  value: 'TN'},
		          {text: 'Jordan', value:'GS'},
		          {text: 'Croatia', value:'HR'},
		          {text: 'Haiti',  value: 'HT'},
		          {text: 'El Salvador', value: 'SV'},
		          {text: 'Hong Kong', value:'HK'},
		          {text: 'Honduras',  value: 'HN'},
		          {text: 'Heard And Mcdonald Islands', value: 'HM'},
		          {text: 'Andorra', value:'AD'},
		          {text: 'Puerto Rico', value:'PR'},
		          {text: 'Palestine',  value: 'PS'},
		          {text: 'Palau',  value: 'PW'},
		          {text: 'Portugal', value: 'PT'},
		          {text: 'Svalbard And Jan Mayen Islands', value:'SJ'},
		          {text: 'Virgin Islands British', value:'VG'},
		          {text: 'Anguilla',  value: 'AI'},
		          {text: 'North Korea', value: 'KP'},
		          {text: 'French Polynesia', value:'PF'},
		          {text: 'Papua New Guinea', value:'PG'},
		          {text: 'Peru',  value: 'PE'},
		          {text: 'Pakistan', value:'PK'},
		          {text: 'Philippines', value:'PH'},
		          {text: 'Pitcairn',  value: 'PN'},
		          {text: 'Poland', value: 'PL'},
		          {text: 'Saint Pierre And Miquelon', value:'PM'},
		          {text: 'Zambia',  value: 'ZM'},
		          {text: 'Western Sahara', value: 'EH'},
		          {text: 'Estonia', value:'EE'},
		          {text: 'Egypt', value:'EG'},
		          {text: 'South Africa',  value: 'ZA'},
		          {text: 'Ecuador',  value: 'EC'},
		          {text: 'Italy', value: 'IT'},
		          {text: 'Angola', value:'AO'},
		          {text: 'Kazakhstan', value:'KZ'},
		          {text: 'Ethiopia',  value: 'ET'},
		          {text: 'Zimbabwe', value: 'ZW'},
		          {text: 'Saudi Arabia', value:'SA'},
		          {text: 'Spain', value:'ES'},
		          {text: 'Eritrea',  value: 'ER'},
		          {text: 'Montenegro', value:'ME'},
		          {text: 'Moldova', value:'MD'},
		          {text: 'Madagascar',  value: 'MG'},
		          {text: 'Morocco', value: 'MA'},
		          {text: 'Monaco', value:'MC'},
		          {text: 'Uzbekistan',  value: 'UZ'},
		          {text: 'Myanmar', value: 'MM'},
		          {text: 'Mali', value:'ML'},
		          {text: 'Macau', value:'MO'},
		          {text: 'Mongolia',  value: 'MN'},
		          {text: 'Marshall Islands',  value: 'MH'},
		          {text: 'United States', value: 'US'},
		          {text: 'United States Minor Outlying Islands', value:'UM'},
		          {text: 'Malta', value:'MT'},
		          {text: 'Malawi',  value: 'MW'},
		          {text: 'Maldives', value: 'MV'},
		          {text: 'Martinique', value:'MQ'},
		          {text: 'Northern Mariana Islands', value:'MP'},
		          {text: 'Montserrat',  value: 'MS'},
		          {text: 'Namibia', value:'NA'},
		          {text: 'Isle Of Man', value:'IM'},
		          {text: 'Uganda', value:'UG'},
		          {text: 'Malaysia',  value: 'MY'},
		          {text: 'Mexico', value: 'MX'},
		          {text: 'Israel', value:'IL'},
		          {text: 'Bulgaria',  value: 'BG'},
		          {text: 'France', value: 'FR'},
		          {text: 'Aruba', value:'AW'},
		          {text: 'Aland Islands', value:'AX'},
		          {text: 'Finland',  value: 'FI'},
		          {text: 'Fiji',  value: 'FJ'},
		          {text: 'Falkland Islands', value: 'FK'},
		          {text: 'Micronesia', value:'FM'},
		          {text: 'Faroe Islands', value:'FO'},
		          {text: 'Nicaragua',  value: 'NI'},
		          {text: 'Netherlands', value: 'NL'},
		          {text: 'Norway', value:'NO'},
		          {text: 'Somalia', value:'SO'},
		          {text: 'New Caledonia',  value: 'NC'},
		          {text: 'Niger', value:'NE'},
		          {text: 'Norfolk Island', value:'NF'},
		          {text: 'Nigeria', value:'NG'},
		          {text: 'New Zealand',  value: 'NZ'},
		          {text: 'Nepal', value: 'NP'},
		          {text: 'Nauru', value:'IL'},
		          {text: 'Niue',  value: 'BG'},
		          {text: 'Mauritania', value: 'FR'},
		          {text: 'Cook Islands', value:'AW'},
		          {text: 'Cote DIvoire', value:'AX'},
		          {text: 'Switzerland',  value: 'FI'},
		          {text: 'Colombia',  value: 'FJ'},
		          {text: 'China', value: 'FK'},
		          {text: 'Cameroon', value:'FM'},
		          {text: 'Chile', value:'FO'},
		          {text: 'Cocos (keeling) Islands',  value: 'NI'},
		          {text: 'Canada', value: 'NL'},
		          {text: 'Congo (brazzaville)', value:'NO'},
		          {text: 'Central African Republic', value:'SO'},
		          {text: 'Congo (kinshasa)',  value: 'NC'},
		          {text: 'Czech Republic', value:'NE'},
		          {text: 'Cyprus', value:'NF'},
		          {text: 'Christmas Island', value:'NG'},
		          {text: 'Serbia',  value: 'NZ'},
		          {text: 'Costa Rica', value: 'NP'},
		          {text: 'Hungary', value:'HU'},
		          {text: 'Cape Verde',  value: 'CV'},
		          {text: 'Cuba', value: 'CU'},
		          {text: 'Swaziland', value:'SZ'},
		          {text: 'Syria', value:'SY'},
		          {text: 'Kyrgyzstan',  value: 'KG'},
		          {text: 'Kenya',  value: 'KE'},
		          {text: 'Suriname', value: 'SR'},
		          {text: 'Kiribati', value:'KI'},
		          {text: 'Cambodia', value:'KH'},
		          {text: 'Saint Kitts And Nevis',  value: 'KN'},
		          {text: 'Comoros', value: 'KM'},
		          {text: 'Sao Tome And Principe', value:'ST'},
		          {text: 'Slovakia', value:'SK'},
		          {text: 'South Korea',  value: 'KR'},
		          {text: 'Slovenia', value:'SI'},
		          {text: 'Saint Helena', value:'SH'},
		          {text: 'Kuwait', value:'KW'},
		          {text: 'Senegal',  value: 'SN'},
		          {text: 'San Marino', value: 'SM'},
		          {text: 'Sierra Leone', value:'SL'},
		          {text: 'Seychelles',  value: 'SC'},
		          {text: 'Solomon Islands', value: 'SB'},
		          {text: 'Cayman Islands', value:'KY'},
		          {text: 'Singapore', value:'SG'},
		          {text: 'Sweden',  value: 'SE'},
		          {text: 'Sudan',  value: 'SD'},
		          {text: 'Dominican Republic', value: 'DO'},
		          {text: 'Dominica', value: 'DM'},
		          {text: 'Djibouti', value:'DJ'},
		          {text: 'Denmark', value:'DK'},
		          {text: 'Germany',  value: 'DE'},
		          {text: 'Yemen', value: 'YE'},
		          {text: 'Austria', value:'AT'},
		          {text: 'Algeria', value:'DZ'},
		          {text: 'Macedonia',  value: 'MK'},
		          {text: 'Uruguay', value:'UY'},
		          {text: 'Mayotte', value:'YT'},
		          {text: 'Mauritius', value:'MU'},
		          {text: 'Tanzania',  value: 'TZ'},
		          {text: 'Saint Lucia', value: 'LC'},
		          {text: 'Laos', value:'LA'},
		          {text: 'Tuvalu',  value: 'TV'},
		          {text: 'Taiwan', value: 'TW'},
		          {text: 'Trinidad And Tobago', value:'TT'},
		          {text: 'Turkey', value:'TR'},
		          {text: 'Sri Lanka',  value: 'LK'},
		          {text: 'Liechtenstein',  value: 'LI'},
		          {text: 'Latvia', value: 'LV'},
		          {text: 'Tonga', value: 'TO'},
		          {text: 'Timor-leste', value:'TL'},
		          {text: 'Luxembourg', value:'LU'},
		          {text: 'Liberia',  value: 'LR'},
		          {text: 'Tokelau', value: 'TK'},
		          {text: 'Thailand', value:'TH'},
		          {text: 'French Southern Lands', value:'TF'},
		          {text: 'Togo',  value: 'TG'},
		          {text: 'Chad', value:'TD'},
		          {text: 'Turks And Caicos Islands', value:'TC'},
		          {text: 'Libya', value:'LY'},
		          {text: 'Vatican City',  value: 'VA'},
		          {text: 'Ascension Island', value: 'AC'},
		          {text: 'Saint Vincent And The Grenadines', value:'VC'},
		          {text: 'United Arab Emirates',  value: 'AE'},
		          {text: 'Venezuela', value: 'VE'},
		          {text: 'Antigua And Barbuda', value:'AG'},
		          {text: 'Afghanistan', value:'AF'},
		          {text: 'Iraq',  value: 'IQ'},
		          {text: 'Virgin Islands U.s.',  value: 'VI'},
		          {text: 'Iceland', value: 'IS'},
		          {text: 'Iran', value: 'IR'},
		          {text: 'Armenia', value:'AM'},
		          {text: 'Albania', value:'AL'},
		          {text: 'Vietnam',  value: 'VN'},
		          {text: 'Netherlands Antilles', value: 'AN'},
		          {text: 'Antarctica', value:'AQ'},
		          {text: 'American Samoa', value:'AS'},
		          {text: 'Argentina',  value: 'AR'},
		          {text: 'Australia', value:'AU'},
		          {text: 'Vanuatu', value:'VU'},
		          {text: 'British Indian Ocean Territory', value:'IO'},
		          {text: 'India',  value: 'IN'},
		          {text: 'Lebanon', value: 'LB'},
		          {text: 'Azerbaijan', value:'AZ'},
		          {text: 'Ireland', value:'IE'},
		          {text: 'Indonesia',  value: 'ID'},
		          {text: 'Panama', value:'PA'},
		          {text: 'Ukraine', value:'UA'},
		          {text: 'Qatar', value:'QA'},
		          {text: 'Mozambique',  value: 'MZ'}
    ]
    
    
});